/**
 * sql-to-ts.mjs
 * Parses the generated universities_seed.sql and outputs src/data/allUniversities.ts
 * so the app can use all 146 universities as local fallback data.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SQL_PATH = join(__dirname, '..', 'supabase', 'universities_seed.sql');
const OUT_PATH = join(__dirname, '..', 'src', 'data', 'allUniversities.ts');

const sql = readFileSync(SQL_PATH, 'utf8');

// Extract each INSERT VALUES block
const insertRegex = /INSERT INTO universities[\s\S]*?VALUES\s*\(([\s\S]*?)\);/g;

const universities = [];
let match;
let id = 1;

while ((match = insertRegex.exec(sql)) !== null) {
  const raw = match[1];

  // Parse the comma-separated values, respecting single-quoted strings
  const values = [];
  let current = '';
  let inStr = false;
  let i = 0;

  while (i < raw.length) {
    const ch = raw[i];
    if (ch === "'" && !inStr) {
      inStr = true;
      i++;
      continue;
    }
    if (ch === "'" && inStr) {
      // check for escaped quote ''
      if (raw[i + 1] === "'") {
        current += "'";
        i += 2;
        continue;
      }
      inStr = false;
      i++;
      continue;
    }
    if (ch === ',' && !inStr) {
      values.push(current.trim());
      current = '';
      i++;
      continue;
    }
    current += ch;
    i++;
  }
  values.push(current.trim());

  // Column order from the INSERT:
  // name, country, country_flag, location, description,
  // tuition_range, tuition_min, tuition_max, ielts_requirement,
  // deadline, has_scholarship, image_url, urgency,
  // ranking, acceptance_rate, student_population,
  // international_students_pct, programs_offered, website, admission_url

  const [
    name, country, country_flag, location, description,
    tuition_range, tuition_min, tuition_max, ielts_requirement,
    deadline, has_scholarship, image_url, urgency,
    ranking, acceptance_rate, student_population,
    international_students_pct, programs_offered, website, admission_url
  ] = values;

  universities.push({
    id: String(id++),
    name,
    country,
    country_flag,
    location,
    description,
    tuition_range,
    tuition_min: Number(tuition_min),
    tuition_max: Number(tuition_max),
    ielts_requirement: Number(ielts_requirement),
    deadline,
    has_scholarship: has_scholarship === 'true',
    image_url,
    urgency: urgency || 'medium',
    ranking: Number(ranking) || null,
    acceptance_rate: Number(acceptance_rate) || null,
    student_population: Number(student_population) || null,
    international_students_pct: Number(international_students_pct) || null,
    programs_offered: Number(programs_offered) || null,
    website,
    admission_url: admission_url && admission_url.length > 0 ? admission_url : null,
    created_at: new Date().toISOString(),
  });
}

const tsContent = `// AUTO-GENERATED by scripts/sql-to-ts.mjs — do not edit manually
// Source: supabase/universities_seed.sql (${universities.length} universities from Hipolabs API)
// Regenerate with: node scripts/sql-to-ts.mjs

import type { University } from '../lib/database.types';

export const allUniversities: University[] = ${JSON.stringify(universities, null, 2)};
`;

writeFileSync(OUT_PATH, tsContent, 'utf8');
console.log(`✅ Generated ${universities.length} universities → ${OUT_PATH}`);
